// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/payment-orders": {
            "post": {
                "description": "Create a payment order and allocate a cryptocurrency address for payment collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "Create a payment order with cryptocurrency address",
                "parameters": [
                    {
                        "description": "Payment Order Details",
                        "name": "payment_order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PaymentAddressRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.PaymentAddressResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid order information",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "Invalid order ID"
                }
            }
        },
        "handlers.PaymentAddressRequest": {
            "type": "object",
            "required": [
                "chain",
                "order_id"
            ],
            "properties": {
                "chain": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                }
            }
        },
        "handlers.PaymentAddressResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "bnb1w7jflwesfnrp0lfgnthkvq55m8gzrlav5ktmyk"
                },
                "chain": {
                    "type": "string",
                    "example": "BNB"
                },
                "created_at": {
                    "type": "string"
                },
                "expire_time": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string",
                    "example": "ORD12345678"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "EC-Wallet API",
	Description:      "API Server for EC-Wallet application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
