basePath: /api
definitions:
  handlers.PaymentAddressRequest:
    properties:
      amount_usd:
        type: number
      chain:
        type: string
      order_id:
        type: string
      token:
        type: string
    required:
    - amount_usd
    - chain
    - order_id
    - token
    type: object
  handlers.PaymentAddressResponse:
    properties:
      address:
        example: 0x6C318c04Ed42cEe76a61870543bf70F55aEf1fdb
        type: string
      chain:
        example: BSC
        type: string
      created_at:
        type: string
      expire_time:
        type: string
      order_id:
        example: ORD12345678
        type: string
      reservation_id:
        type: string
    type: object
info:
  contact: {}
  description: API Server for EC-Wallet application
  title: EC-Wallet API
  version: "1.0"
paths:
  /v1/payment-orders:
    post:
      consumes:
      - application/json
      description: Create a payment order and allocate a cryptocurrency address for
        payment collection
      parameters:
      - description: Payment Order Details
        in: body
        name: payment_order
        required: true
        schema:
          $ref: '#/definitions/handlers.PaymentAddressRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PaymentAddressResponse'
      summary: Create a payment order with cryptocurrency address
      tags:
      - payment
swagger: "2.0"
