basePath: /api
definitions:
  handlers.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Invalid order ID
        type: string
    type: object
  handlers.PaymentAddressRequest:
    properties:
      chain:
        type: string
      order_id:
        type: string
    required:
    - chain
    - order_id
    type: object
  handlers.PaymentAddressResponse:
    properties:
      address:
        example: bnb1w7jflwesfnrp0lfgnthkvq55m8gzrlav5ktmyk
        type: string
      chain:
        example: BNB
        type: string
      created_at:
        type: string
      expire_time:
        type: string
      order_id:
        example: ORD12345678
        type: string
    type: object
info:
  contact: {}
  description: API Server for EC-Wallet application
  title: EC-Wallet API
  version: "1.0"
paths:
  /v1/payment-orders:
    post:
      consumes:
      - application/json
      description: Create a payment order and allocate a cryptocurrency address for
        payment collection
      parameters:
      - description: Payment Order Details
        in: body
        name: payment_order
        required: true
        schema:
          $ref: '#/definitions/handlers.PaymentAddressRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PaymentAddressResponse'
        "400":
          description: Invalid order information
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Create a payment order with cryptocurrency address
      tags:
      - payment
swagger: "2.0"
