basePath: /api
definitions:
  wallet.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Invalid order ID
        type: string
    type: object
  wallet.PaymentAddressResponse:
    properties:
      address:
        example: bnb1w7jflwesfnrp0lfgnthkvq55m8gzrlav5ktmyk
        type: string
      chain:
        example: BNB
        type: string
      created_at:
        type: string
      expire_time:
        type: string
      order_id:
        example: ORD12345678
        type: string
    type: object
info:
  contact: {}
  description: API Server for EC-Wallet application
  title: EC-Wallet API
  version: "1.0"
paths:
  /wallet/v1/payment-address:
    get:
      consumes:
      - application/json
      description: Allocate a BNB address for a specific order number
      parameters:
      - description: Order ID
        in: query
        name: order_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.PaymentAddressResponse'
        "400":
          description: Invalid order ID
          schema:
            $ref: '#/definitions/wallet.ErrorResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/wallet.ErrorResponse'
      summary: Get payment address for an order
      tags:
      - payment
swagger: "2.0"
