// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"ec-wallet/configs"
	"ec-wallet/internal/domain/gorm_repo"
	"ec-wallet/internal/domain/wallet"
	"ec-wallet/internal/infrastructure/database"
	"ec-wallet/internal/infrastructure/repository/gorm_repo"
	"ec-wallet/internal/infrastructure/wallet"
	"gorm.io/gorm"
	"sync"
)

// Injectors from wire.go:

func NewRepository() (gormrepo.Repo, error) {
	gormDB, err := NewDB()
	if err != nil {
		return nil, err
	}
	repo := gormRepoImpl.NewRepository(gormDB)
	return repo, nil
}

func NewWallet() (wallet.Wallet, error) {
	configsConfig := NewConfig()
	repo, err := NewRepository()
	if err != nil {
		return nil, err
	}
	walletWallet := walletservice.NewWalletService(configsConfig, repo)
	return walletWallet, nil
}

// wire.go:

var db *gorm.DB

var dbOnce sync.Once

var config *configs.Config

var configOnce sync.Once

func NewDB() (*gorm.DB, error) {
	var err error
	if db == nil {
		dbOnce.Do(func() {
			db, err = database.PostgresqlConnection()
			if err != nil {
				return
			}
		})
	}
	return db, err
}

func NewConfig() *configs.Config {
	if config == nil {
		configOnce.Do(func() {
			config = configs.NewConfig()
		})
	}
	return config
}
