// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"ec-wallet/internal/domain"
	"ec-wallet/internal/infrastructure/database"
	"ec-wallet/internal/infrastructure/repository/gormRepo"
	"gorm.io/gorm"
	"sync"
)

// Injectors from wire.go:

func NewRepository() (domain.Repository, error) {
	repository := gormRepo.NewRepository()
	return repository, nil
}

// wire.go:

var db *gorm.DB

var dbOnce sync.Once

func NewDB() (*gorm.DB, error) {
	var err error
	if db == nil {
		dbOnce.Do(func() {
			db, err = database.PostgresqlConnection()
			if err != nil {
				return
			}
		})
	}
	return db, err
}
